### ISSUE TITLE
Request for a field-separator argument

### ISSUE THREAD

**Issue by peterjanes** [timbray/topfew#20]
Per #14, "if someone later wants a field-separator argument, make an issue for that."

My particular use case is dealing with large [NDJSON](https://github.com/ndjson/ndjson-spec) streams, where it would be useful to be able to set a `field-separator` of `,`. (There might be cases where a `,` is found within a key or value, but I don't know if multi-character delimiters is a legit request.)

**Comment by timbray** [comment]
I think it'd be a dead easy PR, use [Regexp.Split](https://pkg.go.dev/regexp#Regexp.Split), and then some changes to config.c and runner.c for the new argument. But,  the performance is going to take a pretty severe hit compared to the brute-force state machine in keyfinder.go - that should be measured and documented.

**Comment by timbray** [comment]
Addressed in #23
